debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    spring.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # binding parameter 관찰

spring:
  profiles:
    include: oauth

  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: 23Yong
    password: thisIsTestPw!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie